# Generated by Django 3.2.9 on 2021-12-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('AID', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=10000)),
                ('importTime', models.DateTimeField(auto_now_add=True)),
                ('pubilcTime', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('authorlink', models.CharField(max_length=500)),
            ],
        ),
    ]
