# Generated by Django 3.2.9 on 2021-12-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authorlink',
            new_name='authorLink',
        ),
    ]
