# Generated by Django 3.2.9 on 2021-12-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_rename_authorlink_article_authorlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=100000),
        ),
    ]
