# Generated by Django 3.2.9 on 2021-12-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_alter_article_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.IntegerField()),
                ('TID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('TID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='note',
            field=models.CharField(default='暂无', max_length=10000),
        ),
    ]
