# Generated by Django 3.2.9 on 2021-12-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_auto_20211204_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pubilcTime',
            field=models.DateTimeField(default='待完善'),
        ),
    ]
