# Generated by Django 3.2.9 on 2021-12-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_alter_article_pubilctime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pubilcTime',
        ),
        migrations.AddField(
            model_name='article',
            name='publicTime',
            field=models.DateTimeField(default='1900-01-01'),
        ),
    ]
