# Generated by Django 3.2.9 on 2021-12-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_auto_20211204_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.IntegerField(default=0),
        ),
    ]
