# Generated by Django 3.2.9 on 2021-12-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_collection_collection_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_article',
            name='orderID',
            field=models.IntegerField(default=0),
        ),
    ]
